version: '3'
services:

  demo-service:
    build: ./demo
    container_name: demo-service
    networks:
      - application-network
    ports:
      - "8081:8081"
    environment:
      POSTGES_CONNECTION_STING : root
      DATABASE_DOMAIN: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: root
      POSTGRES_DB: demo
    tty: true
    depends_on:
      - postgres

  postgres:
    image: 'postgres'
    container_name: postgres
    restart: always
    networks:
      -  application-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=demo
    ports:
      - 5432:5432
    tty: true

networks:
  application-network:
    driver: bridge



